[package]
name = "reqwest-pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
thiserror = "1.0.30"
tokio = "1.16.1"
tokio-test = "0.4.2"
