[package]
name = "weatherapi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version="1.9.0",features = ["attributes"]}
clap = "3.0.0-beta.2"
serde = {version="1.0.128", features = ["derive"]}
serde_json = "1.0.66"
surf = "2.2.0"
tide = "0.16.0"
surf-pool = "0.1.2"

[dependencies.aide-proto]
path = "../aide-proto"
